import crypto from 'node:crypto';
import type { DraftsFile, ReviewDraft } from '@meebox/shared';
import type { StateStore } from '@meebox/state-store';

/**
 * KV key for `state/prs/<localId>/drafts.json`. Consistent with the per-PR directory layout,
 * on PR retirement `deleteDir` wipes the whole tree, so drafts need no separate evict.
 */
function draftsKey(prLocalId: string): string {
  return `prs/${prLocalId}/drafts`;
}

/** 12-hex-char short id: same scheme as PR localId, to avoid two id forms in the UI / logs */
function makeDraftId(): string {
  return crypto.randomBytes(8).toString('hex').slice(0, 12);
}

/** Read drafts; returns an empty array if the file is missing (PR entering the draft flow for the first time) */
export async function listDrafts(
  store: StateStore,
  prLocalId: string,
): Promise<ReviewDraft[]> {
  const file = await store.read<DraftsFile>(draftsKey(prLocalId));
  return file?.drafts ?? [];
}

export async function getDraft(
  store: StateStore,
  prLocalId: string,
  draftId: string,
): Promise<ReviewDraft | null> {
  const all = await listDrafts(store, prLocalId);
  return all.find((d) => d.id === draftId) ?? null;
}

/**
 * Write the entire drafts array back to disk. All mutators (create / update / delete /
 * dropPendingFindingDrafts) go through this path, so the "read-modify-write" atomicity falls back on StateStore's
 * tmp + rename.
 */
async function writeDrafts(
  store: StateStore,
  prLocalId: string,
  drafts: ReviewDraft[],
): Promise<void> {
  await store.write<DraftsFile>(draftsKey(prLocalId), {
    schema_version: 1,
    drafts,
  });
}

/**
 * Create a draft. id / createdAt / updatedAt are generated by this function; the caller passes the business fields.
 * Convention: origin='finding' must carry source; origin='manual' must not have source (the upper IPC
 * layer already validates).
 */
export async function createDraft(
  store: StateStore,
  prLocalId: string,
  input: Omit<ReviewDraft, 'id' | 'createdAt' | 'updatedAt' | 'prLocalId'>,
  now: () => Date = () => new Date(),
): Promise<ReviewDraft> {
  const all = await listDrafts(store, prLocalId);
  const nowIso = now().toISOString();
  const draft: ReviewDraft = {
    id: makeDraftId(),
    prLocalId,
    createdAt: nowIso,
    updatedAt: nowIso,
    ...input,
  };
  all.push(draft);
  await writeDrafts(store, prLocalId, all);
  return draft;
}

/**
 * Partial update. Any field patch bumps updatedAt.
 *
 * Automatic status transition: if the patch contains `body` and the draft's current status='pending' → automatically becomes 'edited'
 * (the user touched the original AI suggestion). An explicit patch.status takes precedence over the automatic rule.
 *
 * Returns null if draftId is not found (the caller falls back as needed, does not throw).
 */
export async function updateDraft(
  store: StateStore,
  prLocalId: string,
  draftId: string,
  patch: Partial<Pick<ReviewDraft, 'body' | 'status' | 'posted_remote_id'>>,
  now: () => Date = () => new Date(),
): Promise<ReviewDraft | null> {
  const all = await listDrafts(store, prLocalId);
  const idx = all.findIndex((d) => d.id === draftId);
  if (idx < 0) return null;
  const cur = all[idx]!;
  // body change + pending → automatically 'edited'; explicit patch.status takes precedence
  const autoStatus =
    patch.body !== undefined && patch.body !== cur.body && cur.status === 'pending'
      ? 'edited'
      : undefined;
  const next: ReviewDraft = {
    ...cur,
    ...patch,
    status: patch.status ?? autoStatus ?? cur.status,
    updatedAt: now().toISOString(),
  };
  all[idx] = next;
  await writeDrafts(store, prLocalId, all);
  return next;
}

export async function deleteDraft(
  store: StateStore,
  prLocalId: string,
  draftId: string,
): Promise<void> {
  const all = await listDrafts(store, prLocalId);
  const filtered = all.filter((d) => d.id !== draftId);
  if (filtered.length === all.length) return; // no-op, a nonexistent id does not throw
  await writeDrafts(store, prLocalId, filtered);
}

/**
 * The "re-ingest" rule when /review completes: discard all `pending+finding` drafts.
 *
 * Kept: status ∈ {edited, posted, rejected} or origin='manual' —— decisions the user has already invested in
 * are never overwritten.
 *
 * Returns the number of drafts discarded, which the main side can use to add a "cleaned up N old pending"
 * feedback chip to RunResultView.
 */
export async function dropPendingFindingDrafts(
  store: StateStore,
  prLocalId: string,
): Promise<number> {
  const all = await listDrafts(store, prLocalId);
  const kept = all.filter(
    (d) => !(d.status === 'pending' && d.origin === 'finding'),
  );
  const dropped = all.length - kept.length;
  if (dropped === 0) return 0;
  await writeDrafts(store, prLocalId, kept);
  return dropped;
}
