import type { FindingClosure, FindingClosuresFile } from '@meebox/shared';
import type { StateStore } from '@meebox/state-store';

/**
 * KV key for `state/prs/<localId>/findingClosures.json`. Aligned with the per-PR directory layout;
 * the whole tree is cleared when a PR leaves, so no separate evict is needed. When a re-review /ask
 * "supersedes / revokes" an original finding, a closure is recorded here — independent of local draft
 * semantics, affecting only the closed state of ChatPane finding cards + the two-way link to the re-review card.
 */
function closuresKey(prLocalId: string): string {
  return `prs/${prLocalId}/findingClosures`;
}

/** Read closures; returns an empty array when the file is missing. */
export async function listFindingClosures(
  store: StateStore,
  prLocalId: string,
): Promise<FindingClosure[]> {
  const file = await store.read<FindingClosuresFile>(closuresKey(prLocalId));
  return file?.closures ?? [];
}

async function writeFindingClosures(
  store: StateStore,
  prLocalId: string,
  closures: FindingClosure[],
): Promise<void> {
  await store.write<FindingClosuresFile>(closuresKey(prLocalId), {
    schema_version: 1,
    closures,
  });
}

/**
 * Record a closure (identifying the source finding by (runId, findingId)). When the same source finding
 * already has a closure it is **overwritten** (the most recent re-review wins), avoiding duplicate buildup.
 * createdAt is generated by this function.
 */
export async function addFindingClosure(
  store: StateStore,
  prLocalId: string,
  input: Omit<FindingClosure, 'createdAt'>,
  now: () => Date = () => new Date(),
): Promise<FindingClosure> {
  const all = await listFindingClosures(store, prLocalId);
  const closure: FindingClosure = { ...input, createdAt: now().toISOString() };
  const next = all.filter((c) => !(c.runId === input.runId && c.findingId === input.findingId));
  next.push(closure);
  await writeFindingClosures(store, prLocalId, next);
  return closure;
}

/** Revoke a closure (identified by source finding). No-op if it does not exist; does not throw. */
export async function removeFindingClosure(
  store: StateStore,
  prLocalId: string,
  runId: string,
  findingId: string,
): Promise<void> {
  const all = await listFindingClosures(store, prLocalId);
  const filtered = all.filter((c) => !(c.runId === runId && c.findingId === findingId));
  if (filtered.length === all.length) return;
  await writeFindingClosures(store, prLocalId, filtered);
}
