import { z } from 'zod';
import {
  EDITOR_FONT_SIZE_DEFAULT,
  EDITOR_FONT_SIZE_MAX,
  EDITOR_FONT_SIZE_MIN,
  EDITOR_THEME_IDS,
} from './theme.js';

export const CloneSettingsSchema = z
  .object({
    /**
     * git clone protocol.
     * - pat (default): HTTPS, embeds `<current username>:<PAT>` in the URL (Bitbucket Server convention)
     * - ssh: scp-like `git@<host>:<project>/<repo>.git`, port/key go through the system ssh config
     */
    protocol: z.enum(['pat', 'ssh']).default('pat'),
  })
  .default({});

export const BitbucketServerConnectionSchema = z.object({
  id: z.string().min(1),
  kind: z.literal('bitbucket-server'),
  base_url: z.string().url(),
  display_name: z.string(),
  auth: z.object({
    type: z.literal('pat'),
    token: z.string(),
  }),
  clone: CloneSettingsSchema,
});

/** github.com official REST API base. Used by default when a GitHub connection's base_url is left empty. */
export const GITHUB_DOTCOM_API_BASE = 'https://api.github.com';

export const GitHubConnectionSchema = z.object({
  id: z.string().min(1),
  kind: z.literal('github'),
  /**
   * GitHub REST API base. **Optional**: when empty / omitted, defaults to `https://api.github.com` (github.com);
   * for GitHub Enterprise Server, use `https://<ghe-host>/api/v3`. clone / web host are derived by the adapter
   * (api.github.com → github.com; GHE → same host).
   */
  base_url: z.preprocess(
    (v) => (typeof v === 'string' && v.trim() === '' ? undefined : v),
    z.string().url().default(GITHUB_DOTCOM_API_BASE),
  ),
  display_name: z.string(),
  auth: z.object({
    type: z.literal('pat'),
    token: z.string(),
  }),
  clone: CloneSettingsSchema,
});

/** gitlab.com official REST API v4 base. Used by default when a GitLab connection's base_url is left empty. */
export const GITLAB_DOTCOM_API_BASE = 'https://gitlab.com/api/v4';

export const GitLabConnectionSchema = z.object({
  id: z.string().min(1),
  kind: z.literal('gitlab'),
  /**
   * GitLab REST API v4 base. **Optional**: when empty / omitted, defaults to `https://gitlab.com/api/v4` (gitlab.com);
   * for self-hosted / GitLab Self-Managed, use `https://<host>/api/v4`. clone / web host are derived by the adapter
   * (strip `/api/v4` to get the instance host), and CE vs EE is degraded on capability bits via edition detection (approvals).
   */
  base_url: z.preprocess(
    (v) => (typeof v === 'string' && v.trim() === '' ? undefined : v),
    z.string().url().default(GITLAB_DOTCOM_API_BASE),
  ),
  display_name: z.string(),
  auth: z.object({
    type: z.literal('pat'),
    token: z.string(),
  }),
  clone: CloneSettingsSchema,
});

export const ConnectionSchema = z.discriminatedUnion('kind', [
  GitHubConnectionSchema,
  BitbucketServerConnectionSchema,
  GitLabConnectionSchema,
]);

/**
 * A single LLM profile. Multiple profiles coexist, and `llm.active_id` switches which one is currently in effect.
 * pr-agent uses litellm internally; the provider decides which family of env vars (OPENAI__* / ANTHROPIC__* etc.) is used.
 * `openai-compatible` covers vLLM / DeepSeek / relay / local Ollama OpenAI-compatible endpoints (/v1)
 * and all other schemes compatible with the OpenAI API protocol.
 */
/**
 * Compatibility migration: the deprecated `ollama` provider → `openai-compatible`. Ollama ships an OpenAI-compatible endpoint
 * `/v1`, so route uniformly through the more standard, more stable OpenAI path (litellm `openai/` + OPENAI__API_BASE). base_url
 * gets `/v1` appended (the old ollama default was the native API root `http://localhost:11434`, without `/v1`).
 */
function migrateLegacyLlmProvider(val: unknown): unknown {
  if (val !== null && typeof val === 'object' && !Array.isArray(val)) {
    const o = val as Record<string, unknown>;
    if (o.provider === 'ollama') {
      const raw = typeof o.base_url === 'string' && o.base_url.trim() ? o.base_url.trim() : '';
      const base = (raw || 'http://localhost:11434').replace(/\/+$/, '');
      return {
        ...o,
        provider: 'openai-compatible',
        base_url: /\/v\d+$/.test(base) ? base : `${base}/v1`,
      };
    }
  }
  return val;
}

const LlmProfileObject = z.object({
  /** Stable id, used for UI selection / reference; generated by the renderer on creation (uuid or timestamp) */
  id: z.string().min(1),
  /** Human-readable name, may be empty; the UI falls back to provider+model for display */
  label: z.string().default(''),
  provider: z
    .enum(['openai', 'openai-compatible', 'deepseek', 'anthropic', 'dashscope', 'volcengine-ark', 'cli'])
    .default('openai-compatible'),
  /** OpenAI-family / local service: api_base. Optional, leave empty */
  base_url: z.string().default(''),
  /**
   * pr-agent's `config.model`; litellm accepts a `<provider>/<name>` prefix
   * (e.g. `openai/qwen2.5`, `anthropic/claude-3-5-sonnet`), and also accepts a bare name
   * (`gpt-4o`) which goes to OpenAI.
   */
  model: z.string().default(''),
  /** Primary key; leave empty for local / no-auth services */
  api_key: z.string().default(''),
});

/** An old `ollama` profile is migrated to `openai-compatible` before validation (see migrateLegacyLlmProvider). */
export const LlmProfileSchema = z.preprocess(migrateLegacyLlmProvider, LlmProfileObject);

export type LlmProvider =
  | 'openai'
  | 'openai-compatible'
  | 'deepseek'
  | 'anthropic'
  | 'dashscope' // Alibaba Bailian (DashScope, OpenAI-compatible entry, includes Qwen / DeepSeek-on-DashScope)
  | 'volcengine-ark' // Volcengine Ark (OpenAI-compatible entry, includes Doubao etc.)
  | 'cli'; // Local command line: a locally installed agentic CLI (phase 1: claude code) runs the review, without directly connecting to the API
export type LlmProfile = z.infer<typeof LlmProfileSchema>;

/**
 * Outbound network proxy. Phase 1 supports HTTP proxy only: once enabled, LLM / Bitbucket Server
 * REST / git HTTPS all go through the proxy, only loopback/local (including local Ollama) connect directly automatically; SSH goes through the user's
 * own ~/.ssh/config. The config surface only exposes host/port/Basic Auth.
 * `protocol` is an enum reserved as an extension point (phase 1 only 'http'; adding socks5 etc. is non-breaking for existing configs).
 */
export const ProxySchema = z.object({
  enabled: z.boolean().default(false),
  protocol: z.enum(['http']).default('http'),
  host: z.string().default(''),
  port: z.number().int().min(1).max(65535).default(8080),
  username: z.string().default(''),
  password: z.string().default(''),
});
export type ProxyConfig = z.infer<typeof ProxySchema>;

/**
 * Local API service listener (see docs/arch/04-integration/01-service-api.md). Disabled by default, zero exposure surface; enabling **enforces**
 * bearer token authentication (the token is auto-generated by the main process on enable when empty). `host` defaults to loopback only (127.0.0.1), and can be set to
 * `0.0.0.0` to expose it to the LAN — high risk, needs a security warning. `port` has a fixed safe default of 18765 (10000+, avoiding common dev ports and below
 * the ephemeral port range). The token is stored in plaintext on disk (same as the existing credential policy, abstracted via SecretStore, never entering logs).
 */
export const ServiceSchema = z.object({
  enabled: z.boolean().default(false),
  host: z.string().default('127.0.0.1'),
  port: z.number().int().min(1).max(65535).default(18765),
  token: z.string().default(''),
});
export type ServiceConfig = z.infer<typeof ServiceSchema>;

/**
 * LLM context length (token): the global cap for trimming input content, passed through to pr-agent `CONFIG__MAX_MODEL_TOKENS` /
 * `CONFIG__CUSTOM_MODEL_MAX_TOKENS`. Default 128000 (matching the context of modern mainstream models); **does not apply to local CLI mode**
 * (the CLI tool manages its own context, see @meebox/pr-agent-bridge). Range 32k~1M.
 */
export const LLM_CONTEXT_TOKENS_MIN = 32000;
export const LLM_CONTEXT_TOKENS_MAX = 1000000;
export const LLM_CONTEXT_TOKENS_DEFAULT = 128000;

export const ConfigSchema = z.object({
  /**
   * The language used by the UI and pr-agent output (ISO locale, e.g. 'zh-CN' / 'en-US' / 'ja-JP' / 'de-DE').
   * **Empty string by default = automatic**: matched by `resolveLanguage` against the OS preferred language, falling back to English when there is no suitable match.
   * When non-empty, follows the explicit choice. Passed through to the container `CONFIG__RESPONSE_LANGUAGE` (the resolved effective value).
   */
  language: z.string().default(''),
  /**
   * Appearance preferences (pure frontend display items such as global theme / editor font; the main process only sets the native window themeSource based on the theme).
   */
  appearance: z
    .object({
      /**
       * Global theme (shared by the Monaco editor + the entire GUI chrome): 'auto' follows the system dark / light (default, dark → Dark
       * Modern, light → Light Modern), the rest are built-in / third-party theme ids (see @meebox/shared EDITOR_THEME_OPTIONS).
       * The theme's inferred light / dark is written to data-theme to drive the semantic color palette and derive the chrome structural colors; resolution see renderer/src/theme.
       */
      editor_theme: z.enum(EDITOR_THEME_IDS).default('auto'),
      /**
       * Editor monospace font family (CSS font-family, comma-separated candidates allowed). **Empty by default** = use the built-in mono font stack;
       * when non-empty, overrides the monospace text font for the editor and the whole app.
       */
      editor_font_family: z.string().default(''),
      /** Editor font size (px). Bounded to a reasonable range (see EDITOR_FONT_SIZE_MIN/MAX), default 14; further fine-tuned per platform. */
      editor_font_size: z
        .number()
        .int()
        .min(EDITOR_FONT_SIZE_MIN)
        .max(EDITOR_FONT_SIZE_MAX)
        .default(EDITOR_FONT_SIZE_DEFAULT),
    })
    .default({}),
  workspace: z
    .object({
      repos_dir: z.string().default('~/.code-meeseeks/repos'),
    })
    .default({}),
  /**
   * The high-level Agent (see docs/arch/02-agent/01-agent.md). The Agent directory is the Agent's complete personality and knowledge source:
   * `<agent.dir>/` contains SOUL.md / AGENTS.md / MEMORY.md / USER.md and the rules/ subdirectory
   * (rule bodies, match semantics see @meebox/rules).
   *
   * The Agent has no separate enable switch — it is usable as long as an LLM is configured and pr-agent is ready. When dir is empty (default) it falls back to
   * the default location under the working directory (`~/.code-meeseeks/agent`, idempotently scaffolded at startup); a custom path can point to a
   * git repo so a team can share context.
   */
  agent: z
    .object({
      dir: z.string().default(''),
      /** Per-session step cap (defaults to a small value; see docs/arch/02-agent/02-session.md "Agentifying the session"). */
      max_steps: z.number().int().min(1).max(50).default(8),
      /** Strict length cap for the summary (characters). */
      summary_max_chars: z.number().int().min(100).max(4000).default(800),
      /**
       * AutoPilot pre-review (see docs/arch/02-agent/03-autopilot.md "AutoPilot"). Disabled by default, can be enabled from the status bar.
       * When enabled=false the scheduling logic does not run at all.
       */
      autopilot: z
        .object({
          enabled: z.boolean().default(false),
          // The evaluation cadence is aligned with polling (evaluated once per poller tick), no separate minimum interval; admission gating + ledger dedup prevent repeats.
          /** Per-batch cap on the number of PRs for LLM decisions. */
          batch_size: z.number().int().min(1).max(50).default(10),
          /**
           * Per-item write permission grants (empty by default = deny all). E.g. 'approve' / 'needs_work' /
           * 'publish_comment'; released at runtime after hard validation against the red lines (see "Tool mutation red lines").
           */
          grants: z.array(z.string()).default([]),
        })
        .default({}),
      /**
       * Agent behavior strategy (an extension point; subsequent behavior switches are merged here). Applies to the automatic review micro-flow (shared by manual auto-review +
       * AutoPilot), not exclusive to AutoPilot. Current items:
       * - auto_followup: whether to enable **automatic follow-up questions** (conditional /ask) during the review run phase. When off, the review micro-flow skips
       *   the judge + asks two steps and summarizes directly, saving one judge LLM call and potential follow-up cost (saves token). On by default,
       *   consistent with historical behavior.
       * - max_followup_asks: cap on the number of automatic follow-up questions (hard cap on conditional /ask).
       */
      strategy: z
        .object({
          auto_followup: z.boolean().default(true),
          /**
           * Cap on the number of automatic follow-up questions (hard cap on conditional /ask, 0~5, default 2). Effective only when auto_followup is on;
           * 0 is equivalent to off (the switch already controls enable/disable independently, so the UI dropdown offers only 1~5, not 0, to avoid ambiguity).
           */
          max_followup_asks: z.number().int().min(0).max(5).default(2),
          /**
           * Cap on the number of code suggestions / review findings generated per task (2~8, default 4). Uniformly constrains three places:
           * - /review: pr-agent `pr_reviewer.num_max_findings` (hard cap);
           * - /improve: pr-agent `pr_code_suggestions.num_code_suggestions` (hard cap);
           * - /ask: a prompt-layer soft constraint on the structured `<suggestions>` section (the model generally complies, a rare few may exceed).
           */
          max_code_suggestions: z.number().int().min(2).max(8).default(4),
        })
        .default({}),
    })
    .default({}),
  poller: z
    .object({
      interval_seconds: z.number().int().min(30).default(300),
    })
    .default({}),
  /** Outbound network proxy. Disabled by default = all direct connections, equivalent to historical behavior. */
  proxy: ProxySchema.default({}),
  /**
   * Version update check. At startup (and manually from the settings page) queries the latest stable GitHub Releases version and compares it against the current version,
   * only **notifying** the user to download when a newer version exists (no auto download / install). check_enabled=false disables the check.
   */
  update: z
    .object({
      check_enabled: z.boolean().default(true),
    })
    .default({}),
  /** Local API service listener (disabled by default). See {@link ServiceSchema} above. */
  service: ServiceSchema.default({}),
  /**
   * Notifications (see docs/arch/03-gui/03-notifications.md). enabled is the master switch; when off, neither system notifications pop nor does the dock badge light up.
   * The other items control per event type whether a system notification (toast) pops: new_pr / reply / mention target scenarios like "awaiting my review";
   * authored_* target PRs "I authored" (I am the author) — new comment / marked needs work / merge conflict appeared. The macOS dock "awaiting response" count
   * badge has no separate switch — enabled by default along with the master switch. System notifications are subject to OS permission — when the user disables them in system settings, the app silently degrades.
   */
  notifications: z
    .object({
      enabled: z.boolean().default(true),
      /** Pop a system notification when a new PR arrives */
      new_pr: z.boolean().default(true),
      /** Pop a system notification when a comment reply is received */
      reply: z.boolean().default(true),
      /** Pop a system notification when @-mentioned in a comment */
      mention: z.boolean().default(true),
      /** Pop a system notification when a PR I authored receives a new comment from someone else */
      authored_comment: z.boolean().default(true),
      /** Pop a system notification when a PR I authored is marked "needs work" by a review */
      authored_needs_work: z.boolean().default(true),
      /** Pop a system notification when a PR I authored has a merge conflict */
      authored_conflict: z.boolean().default(true),
    })
    .default({}),
  /**
   * pr-agent runtime strategy selection.
   * - 'auto' (default): prefer the embedded runtime (bundled with the app, always available on a normal install), and if missing
   *   fall back to probing the system local-cli;
   * - explicit 'embedded' / 'local-cli': force that strategy, convenient for advanced users to switch to their own system CLI.
   */
  pr_agent: z
    .object({
      strategy: z.enum(['auto', 'embedded', 'local-cli']).default('auto'),
      /**
       * Review task concurrency (1~8, default 2). Under embedded / local-cli, each run has an independent worktree +
       * an independent child process, concurrency-safe; the cap throttles LLM rate limits / local machine resources. Adjustable from the settings page (config:setMaxConcurrency
       * hot-swaps the queue cap), or editable by hand in config.yaml.
       */
      max_concurrency: z.number().int().min(1).max(8).default(2),
    })
    .default({}),
  connections: z.array(ConnectionSchema).default([]),
  /**
   * The single currently **active** connection id (only one is active at a time, see the settings page). When empty / no matching connection is found,
   * no connection is polled (the UI guides the user to enable one). The connections array retains all configs, only the active
   * one gets an adapter built and polled; places that look up a connection by id still read the full set, so historical PRs are unaffected.
   */
  active_connection_id: z.string().default(''),
  llm: z.preprocess(
    // Compatibility with the old single-config shape: the initial M3-C version used { provider, base_url, model, api_key }
    // directly as the llm field; it is now { profiles: [...], active_id }. Detecting the old shape
    // automatically wraps it into a single profile with id='default'.
    (val) => {
      if (
        val !== null &&
        typeof val === 'object' &&
        !Array.isArray(val) &&
        !('profiles' in val) &&
        ('provider' in val ||
          'model' in val ||
          'api_key' in val ||
          'base_url' in val)
      ) {
        const o = val as Record<string, unknown>;
        const oldProvider = typeof o.provider === 'string' ? o.provider : '';
        // azure is deprecated, convert to openai-compatible (Azure is essentially the OpenAI API + a custom base_url)
        const provider = (
          [
            'openai',
            'openai-compatible',
            'deepseek',
            'anthropic',
            'ollama',
            'dashscope',
            'volcengine-ark',
            'cli',
          ] as const
        ).includes(oldProvider as LlmProvider)
          ? (oldProvider as LlmProvider)
          : 'openai-compatible';
        return {
          profiles: [
            {
              id: 'default',
              label: '默认',
              provider,
              base_url: typeof o.base_url === 'string' ? o.base_url : '',
              model: typeof o.model === 'string' ? o.model : '',
              api_key: typeof o.api_key === 'string' ? o.api_key : '',
            },
          ],
          active_id: 'default',
        };
      }
      return val;
    },
    z
      .object({
        /** The multiple LLM profiles the user has saved (each with its own provider/model/base_url/key) */
        profiles: z.array(LlmProfileSchema).default([]),
        /**
         * The currently selected profile id. When it is an empty string or no matching profile is found, pragent:run
         * injects no LLM env and pr-agent falls back to reading the shell environment variables.
         */
        active_id: z.string().default(''),
        /**
         * The context length cap (token) for trimming input content. Passed through to pr-agent CONFIG__MAX_MODEL_TOKENS /
         * CONFIG__CUSTOM_MODEL_MAX_TOKENS; oversized changes are truncated by this to fit the model. **Does not apply to local CLI mode**
         * (the CLI tool manages its own context). Default 128000, range 32k~1M (see @meebox/pr-agent-bridge).
         */
        context_tokens: z
          .number()
          .int()
          .min(LLM_CONTEXT_TOKENS_MIN)
          .max(LLM_CONTEXT_TOKENS_MAX)
          .default(LLM_CONTEXT_TOKENS_DEFAULT),
      })
      .default({}),
  ),
});

export type Config = z.infer<typeof ConfigSchema>;
export type Connection = z.infer<typeof ConnectionSchema>;
export type BitbucketServerConnection = z.infer<typeof BitbucketServerConnectionSchema>;
export type GitHubConnection = z.infer<typeof GitHubConnectionSchema>;
